apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-volume-config
data:
  config.yml: |-
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: {{.registryCacheType}}
      gcs:
        bucket: {{.registryGcsBucket}}
        keyfile: /etc/google_data/{{.registryGceSecretKeyName}}
        rootdirectory: {{.registryGcsPrefix}}
        chunksize: 5242880
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
    redis:
      addr: redis:6379
      db: 0
      dialtimeout: 10ms
      readtimeout: 10ms
      writetimeout: 10ms
      pool:
        maxidle: 16
        maxactive: 64
        idletimeout: 300s
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: docker-registry
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: {{.imageRegistry}}/{{.imageName}}:{{.dockerTag}}
        imagePullPolicy: {{.pullPolicy}}
        name: docker-registry
        env:
        - name: REGISTRY_HTTP_SECRET
          valueFrom:
            secretKeyRef:
              name: {{.registryHttpSecretName}}
              key: {{.registryHttpSecretKeyName}}
        ports:
        - containerPort: 5000
          hostPort: 5000
          protocol: TCP
        volumeMounts: 
        - mountPath: /etc/google_data
          name: google-vol
          readOnly: true
      volumes:
        - name: google-vol
          secret:
            secretName: {{.registryGceSecretName}}
      dnsPolicy: {{.dnsPolicy}}
      restartPolicy: {{.restartPolicy}}
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
spec:
  ports:
  - name: docker-registry
    port: {{.externalPort}}
    protocol: TCP
    targetPort: 5000
  selector:
    name: docker-registry
  sessionAffinity: {{.sessionAffinity}}
  type: LoadBalancer

